### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ioeshu** [alvarowolfx/gcloud-iot-edge-tensorflow#19]
when I try to run the edge-server code, I'm getting this error

```
(node:228257) UnhandledPromiseRejectionWarning: Error: The dtype of dict['image_tensor'] provided in model.execute(dict) must be int32, but was float32
    at Object.assert (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:708:15)
    at /media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7131:28
    at Array.forEach (<anonymous>)
    at GraphExecutor.checkInputShapeAndType (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7118:29)
    at GraphExecutor.<anonymous> (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6921:34)
    at step (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:77:23)
    at Object.next (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:58:53)
    at /media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:51:71
    at new Promise (<anonymous>)
    at __awaiter (/media/eswar/dev/SEM/gcloud-iot-edge-tensorflow/edge-server/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:47:12)
(node:228257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:228257) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by liuqianjin** [comment]
你好！你的邮件刘仟金已经收到，感谢~
